version: "3.8"
services:
  web:
    build:
      context: ./frontend
      dockerfile:
    volume:
      - react_build:/frontend/build
    ports:
      - "8080:8080"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
    command: gunicorn core.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.config:/etc/nginx/conf.d/default.conf:ro
      - react_build:/var/www/react

volume: react_build
